spring:
  mvc:  
    view:  
      prefix: /WEB-INF/views/
      suffix: .jsp

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/acappella
    username: postgres
    password: shuhei

server:
  contextPath: /ac
  
security:
  basic:
    enabled: false